### PR TITLE
Fixes main in package.json

### PR DESCRIPTION
**Pull request by alexgorbatchev**
Thanks for the great module, current `require('to-time')` is broken due to invalid `main` value.

### CODE REVIEW

**Comment by hafuta** [comment]
@alexgorbatchev thanks for the feedback and letting me know about this issue.
I'm wondering if the main file should point to src/index.js or lib/to-time.js which is already bundled with the bignumber.js dependency.
For the browser I think it is better to use the bundled file but I'm not sure if this is the case for server-side work, if it is okay for the server side to work with the bundled file (I've tested it and it works fine) I can move the bignumber.js dependency to dev-dependency.

What do you think?

**Comment by alexgorbatchev** [comment]
`npm install to-time` will install `bignumber.js` as well if it's not already installed.

The only usecase for the `lib/to-time.js` is to directly load the file with the `<script/>` tag. Any other time, a build system will bundle everything together correctly.

If anything, my advice would be to completely get rid of the `lib/to-time.js` and let users bundle everything on their own. Very few users (nearly zero IMO) will actually use `lib/to-time.js` due to modern systems being all having custom build system based on CommonJS.

Does that make sense?

**Comment by hafuta** [comment]
@alexgorbatchev make sense but for now I will also keep the bundled file, 
There are still many users/developers or small projects that are not using any bundler or a dependency manager.

Thanks!

**Comment by alexgorbatchev** [comment]
Could you please npm publish? Also, I suggest going to `1.0.0` :)

**Comment by hafuta** [comment]
@alexgorbatchev already did it, I'm just finishing one additional thing and then publishing it as 1.0.0,
Now if you pass invalid time unit like month you get an error from bignumber, I'm now checking that the time unit exists in the units map so it will throw more informative error like "Invalid unit: month".

**Pull request merged**
